# Generated by Django 3.0.2 on 2021-06-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAreas',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('class_title', models.CharField(blank=True, max_length=54, null=True)),
            ],
            options={
                'db_table': 'class_streams',
            },
        ),
    ]
