# Generated by Django 3.0.2 on 2021-06-21 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kilimo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClientAreas',
            new_name='ClassStreams',
        ),
    ]
