# Generated by Django 3.0.2 on 2021-06-21 13:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kilimo_app', '0002_auto_20210621_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='classstreams',
            name='students_number',
            field=models.CharField(blank=True, max_length=54, null=True),
        ),
        migrations.AddField(
            model_name='classstreams',
            name='teacher',
            field=models.CharField(blank=True, max_length=54, null=True),
        ),
        migrations.AlterField(
            model_name='classstreams',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
