# Generated by Django 3.0.2 on 2021-06-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kilimo_app', '0005_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_class',
            field=models.CharField(blank=True, max_length=54, null=True),
        ),
    ]
