# Generated by Django 3.0.2 on 2021-06-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kilimo_app', '0006_auto_20210621_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_class',
            field=models.CharField(max_length=54),
        ),
    ]
