# Generated by Django 3.0.2 on 2021-06-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kilimo_app', '0007_auto_20210621_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_class',
        ),
        migrations.AddField(
            model_name='student',
            name='students_class',
            field=models.CharField(blank=True, max_length=54, null=True),
        ),
    ]
