# Generated by Django 3.0.2 on 2021-06-21 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kilimo_app', '0008_auto_20210621_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='students_class',
            new_name='student_class',
        ),
    ]
